#pragma once
enum class ExpressionType : unsigned char{
	UNARY_OPERATOR_EXPRESSION,
	BINARY_CALCULATE_EXPRESSION,
	BINARY_COMPARE_EXPRESSION,
	ASSIGNMENT_EXPRESSION,
	FUNCTION_EXPRESSION,
	FUNCTION_INVOCATION_EXPRESSION,
	PARAMETER_EXPRESSION,
	EXECUTE_CPP_CODE_EXPRESSION,
	PRINT_EXPRESSION,
	THIS_EXPRESSION,
	MEMBER_EVALUATE_EXPRESSION,
	VARIABLE_EXPRESSION,
	STRING_EXPRESSION,
	INTEGER_EXPRESSION,
	FLOAT_EXPRESSION,
	LIST_EXPRESSION
};