#pragma once
enum class ExpressionType : unsigned char{
	MULTI_VALUE_EXPRESSION,
	UNARY_OPERATOR_EXPRESSION,
	BINARY_CALCULATE_EXPRESSION,
	BINARY_COMPARE_EXPRESSION,
	ASSIGNMENT_EXPRESSION,
	CALL_EXPRESSION,
	TEMPLATE_CALL_EXPRESSION,
	VARIABLE_EXPRESSION,
	TEMPLATE_VARIABLE_EXPRESSION,
	STRING_EXPRESSION,
	INTEGER_EXPRESSION,
	FLOAT_EXPRESSION
};